# -*- coding: utf-8 -*-
"""Factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CDzAgVBnuEuEConNbVURnkP0DkXCSNal
"""

n=5
f=1
for i in range(1,n+1):
 f=f*i
print("Factorial of {} is {}".format(n,f))