# -*- coding: utf-8 -*-
"""IncometTax_ques.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cr46oi6fMnt73FoF1PLyzkSDGDhxYUd3

5) Income Tax
"""

income = 1100000
if (income <= 300000):
  print("No income tax required")
  print("Salary=",income)
elif income > 300000 and income <= 500000:
  tax = income*0.05
  Salary = income - tax
  print("Income tax required",tax)
  print("Salary=",Salary) 
elif income > 500000 and income <= 1000000:
  tax = income*0.10
  Salary = income - tax
  print("Income tax required",tax)
  print("Salary=",Salary) 
elif income > 1000000 and income <= 1500000:
  tax = income*0.20
  Salary = income - tax
  print("Income tax required",tax)
  print("Salary=",Salary)  
elif income > 1500000 and income <= 2000000:
  tax = income*0.25
  Salary = income - tax
  print("Income tax required",tax)
  print("Salary=",Salary)  
else:
  tax = income*0.25
  Salary = income - tax
  print("Income tax required",tax)
  print("Salary=",Salary)