# -*- coding: utf-8 -*-
"""Pallindrome_No & Amstrong_no.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PauP_i04V-vlwTdH7Mz1iFPlvgKils1s

1) Palindrome No
"""

n=int(input("Enter a number:"))
temp=n
rev=0
while(n>0):
    d=n%10
    rev=rev*10+d
    n=n//10
if(temp==rev):
    print("The number is palindrome")
else:
    print("Not a palindrome")

"""2) Amstrong No"""

num = int(input("Enter a number: "))
sum = 0
temp = n
while temp > 0:
   d = temp % 10
   sum += d ** 3
   temp //= 10
if n == sum:
   print("The no is an Armstrong number")
else:
   print("The no is not an Armstrong number")