# -*- coding: utf-8 -*-
"""Python1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YqUlcjSE6xykPRdsw_-lzJofzwXo8XLL
"""

a = 5
b= "Samiran"
c = 5.45

var = 5

var

VAR = 26

var

VAR

a,b,c,d,e,pi = 5,3,56,"Ram","Rajan",3.14

type(pi)

b = int(b)

type(b)

x = 10
y = 15

x + y

y - x

x * y

x = 7
y = 2

# absolute division
x/y

# floor division
x // y

x%y

x ** 2

pwd