# -*- coding: utf-8 -*-
"""Python2_codes1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cr46oi6fMnt73FoF1PLyzkSDGDhxYUd3

1) No is +ve or -ve
"""

a = 5
if a>0:
   print("The no is a +ve no")
elif a<0:
   print("It is a -ve no")
else:
   print("The no is neither a +ve no nor a negative no")

"""2) Find whether the no is greater or not"""

a = 5
b = 10
if a>b:
   print("a is greater than b")
elif a<b:
   print("a  is less than b")
else :
   print("a is equal to b")

"""3) Find whether the no is even or not"""

a = 10
if a%2 == 0:
   print("It is an even no")
else:
   print("It is an odd no")

"""4) Find the greatest of all the no's"""

a = 5
b = 10
c = 15
if (a > b) and (a > c):
   largest = a
elif (b > a) and (b > c):
   largest = b
else:
   largest = c
print("The largest number is",largest)